<a href="https://colab.research.google.com/github/seanzhu815/404/blob/main/404assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  9 12:25:14 2020

@author: gaojx
"""
"""
HW3 Junxiong Gao, import the package

"""
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
"""
Read the data, this hw does not require many structure, everythins is in \
numpy

"""


'\nRead the data, this hw does not require many structure, everythins is in numpy\n\n'

# 1&2&3&4

In [2]:
data = pd.read_excel('/content/drive/MyDrive/MGTF404/PredictorData2018_GoyalWelch.xlsx')
data = data.loc[np.floor(data['yyyymm']/100)>=1926,:]

price = np.array(data['Index'])
dividend = np.array(data['D12'])
earning = np.array(data['E12'])

dp = np.log(dividend/price)
ep = np.log(earning/price)
rf = 12*np.log(np.array(data['Rfree'])+1)
retvw = 12*np.log(np.array(data['CRSP_SPvw'])+1)
retvwx = 12*np.log(np.array(data['CRSP_SPvwx'])+1)

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")


In [4]:
retvw.mean()

0.09376193499004529

In [5]:
retvwx.mean()

0.05575018696417264

In [6]:
retvw.std()

0.6464539882175661

In [7]:
retvwx.std()

0.6498230895358073

#5

In [9]:
data

yyyymm    Index        D12      E12       b/m     tbl     AAA     BAA  \
660   192601    12.74   0.607500    1.249  0.387671  0.0349  0.0482  0.0609   
661   192602    12.18   0.615000    1.248  0.394363  0.0318  0.0477  0.0602   
662   192603    11.46   0.622500    1.248  0.494091  0.0314  0.0479  0.0605   
663   192604    11.72   0.630000    1.247  0.482917  0.0308  0.0474  0.0598   
664   192605    11.81   0.637500    1.246  0.483860  0.0317  0.0471  0.0586   
...      ...      ...        ...      ...       ...     ...     ...     ...   
1771  201808  2901.52  52.338996  130.390  0.229618  0.0203  0.0388  0.0477   
1772  201809  2913.98  52.338996  130.390  0.225335  0.0213  0.0398  0.0488   
1773  201810  2711.74  53.748178  132.390  0.237380  0.0225  0.0414  0.0507   
1774  201811  2760.17  53.748178  132.390  0.233451  0.0233  0.0422  0.0522   
1775  201812  2506.85  53.748178  132.390  0.255578  0.0237  0.0402  0.0513   

         lty      ntis     Rfree      infl     ltr   corpr      svar  csp  \
660   0.0374       NaN  0.002908  0.000000  0.0138  0.0072  0.000857  NaN   
661   0.0372       NaN  0.002650  0.000000  0.0063  0.0045  0.001099  NaN   
662   0.0371       NaN  0.002617 -0.005587  0.0041  0.0084  0.006016  NaN   
663   0.0368       NaN  0.002567  0.005618  0.0076  0.0097  0.001466  NaN   
664   0.0369       NaN  0.002642 -0.005587  0.0014  0.0044  0.000690  NaN   
...      ...       ...       ...       ...     ...     ...       ...  ...   
1771  0.0293 -0.021495  0.001692  0.000556  0.0152  0.0058  0.000471  NaN   
1772  0.0334 -0.020871  0.001775  0.001162 -0.0518 -0.0120  0.000230  NaN   
1773  0.0352 -0.021222  0.001875  0.001767 -0.0204 -0.0323  0.004578  NaN   
1774  0.0317 -0.024593  0.001942 -0.003349  0.0505  0.0071  0.002838  NaN   
1775  0.0284 -0.019217  0.001975 -0.003194  0.0481  0.0370  0.006793  NaN   

      CRSP_SPvw  CRSP_SPvwx  
660   -0.001783   -0.003980  
661   -0.033296   -0.037876  
662   -0.057708   -0.062007  
663    0.038522    0.034856  
664    0.013623    0.009070  
...         ...         ...  
1771   0.032938    0.030647  
1772   0.005138    0.003758  
1773  -0.068409   -0.069492  
1774   0.019980    0.017477  
1775  -0.090928   -0.092457  

[1116 rows x 18 columns]

In [44]:
predictor = [dp,ep,rf]
"""
Property of dp and ep

"""
T = np.size(dp,0)-1
phi = []
R2 = []
u = np.zeros((T,len(predictor)))
for i in np.arange(len(predictor)):
    x = predictor[i]
    model = sm.OLS(x[1:],sm.add_constant(x[:-1]))
    res = model.fit()
    phi = np.hstack((phi,res.params[1]))
    R2 = np.hstack((R2,res.rsquared))
    u[:,i] = res.resid
    


In [26]:
# You are asked to correct the bias itself and also repeat this for the predictive regression.
#bias
bias=(1+3*phi)/T

phi_unbias=phi+bias

In [27]:
phi_unbias

array([0.99673152, 0.99048028, 0.99671496])

# 6

In [46]:
beta=[]
R2_predict=[]
e=np.zeros((T,len(predictor)))
for i in np.arange(len(predictor)):
  x = predictor[i]
  model = sm.OLS(retvw[1:],sm.add_constant(x[:-1]))
  res=model.fit()
  beta = np.hstack((beta,res.params[1]))
  R2_predict = np.hstack((R2_predict,res.rsquared))
  e[:,i] = res.resid

In [56]:
beta

array([ 0.0602789 ,  0.11587401, -0.0234477 ])

In [48]:
#bias
covar=[]
for i in np.arange(len(predictor)):
  a=np.cov(u[:,i],e[:,i])
  covar=np.hstack((covar,a[0,1]))

In [49]:
bias_predict=bias*covar/np.var(u,0)

In [51]:
beta_unbias=beta-bias_predict

In [52]:
beta_unbias

array([0.1013714 , 0.14237324, 0.01644003])